allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@radix-ui/react-use-controllable-state@1.2.6'
  - '@radix-ui/react-use-effect-event@0.0.5'
  - '@radix-ui/react-use-layout-effect@1.1.4'
  - '@ai-sdk/gateway@3.0.162'
  - '@ai-sdk/react@3.0.242'
  - ai@6.0.240
